// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp2ARb7CIVrTSwRYOpYzsBAqsebBMI7JA',
    appId: '1:33387590395:web:726a1cd293bf4daf98765e',
    messagingSenderId: '33387590395',
    projectId: 'reclicaqui',
    authDomain: 'reclicaqui.firebaseapp.com',
    storageBucket: 'reclicaqui.appspot.com',
    measurementId: 'G-431D7E2NBT',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz5EjufuxW1KRRUZ5Qm4yrdMv8cFYr0BI',
    appId: '1:33387590395:android:cc64bac9de62c3ee98765e',
    messagingSenderId: '33387590395',
    projectId: 'reclicaqui',
    storageBucket: 'reclicaqui.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Go5rwbmrR_NmE2gLYnRNlenQzrYFptQ',
    appId: '1:33387590395:ios:5d411992b90b541998765e',
    messagingSenderId: '33387590395',
    projectId: 'reclicaqui',
    storageBucket: 'reclicaqui.appspot.com',
    iosBundleId: 'com.example.reciclaqui',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Go5rwbmrR_NmE2gLYnRNlenQzrYFptQ',
    appId: '1:33387590395:ios:5d411992b90b541998765e',
    messagingSenderId: '33387590395',
    projectId: 'reclicaqui',
    storageBucket: 'reclicaqui.appspot.com',
    iosBundleId: 'com.example.reciclaqui',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp2ARb7CIVrTSwRYOpYzsBAqsebBMI7JA',
    appId: '1:33387590395:web:cb683fb3b08e1bed98765e',
    messagingSenderId: '33387590395',
    projectId: 'reclicaqui',
    authDomain: 'reclicaqui.firebaseapp.com',
    storageBucket: 'reclicaqui.appspot.com',
    measurementId: 'G-WHR2EGTGCQ',
  );
}